source 'https://rubygems.org'
ruby '2.0.0'
gem 'sinatra'
gem 'erubis'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-mysql-adapter'
gem 'thin'
gem 'redcarpet'
gem 'dm-postgres-adapter'

